version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - wukongcheng
      - chengwenxi
      - guoshijiang
      - FletcherMan
      - silmaj
      - Zer0ne001
      - bradyjoestar
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - wukongcheng
      - chengwenxi
      - guoshijiang
      - FletcherMan
      - silmaj
      - Zer0ne001
      - bradyjoestar
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
