// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitnetwork/rvesting/v1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the module's genesis state
type GenesisState struct {
	// module parameters invariant
	Params     Params                                   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	From       string                                   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	InitReward github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=init_reward,json=initReward,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"init_reward"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f2e4832c9e0a14d, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GenesisState) GetInitReward() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.InitReward
	}
	return nil
}

// Params defines the rvesting module params
type Params struct {
	// parameter to enable the vesting of staking reward
	EnableVesting  bool                                     `protobuf:"varint,1,opt,name=enable_vesting,json=enableVesting,proto3" json:"enable_vesting,omitempty"`
	PerBlockReward github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=per_block_reward,json=perBlockReward,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"per_block_reward"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f2e4832c9e0a14d, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnableVesting() bool {
	if m != nil {
		return m.EnableVesting
	}
	return false
}

func (m *Params) GetPerBlockReward() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.PerBlockReward
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "bitnetwork.rvesting.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "bitnetwork.rvesting.v1.Params")
}

func init() {
	proto.RegisterFile("bitnetwork/rvesting/v1/genesis.proto", fileDescriptor_6f2e4832c9e0a14d)
}

var fileDescriptor_6f2e4832c9e0a14d = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0x86, 0x45, 0xdb, 0x30, 0x5a, 0xba, 0x35, 0x0a, 0xa1, 0x28, 0x5c, 0x0f, 0xb4, 0x61, 0xb4,
	0x80, 0x16, 0x93, 0x96, 0xbb, 0x76, 0x52, 0x87, 0x02, 0x9d, 0x0a, 0x05, 0xc8, 0x90, 0xc5, 0x20,
	0x65, 0x46, 0x21, 0x6c, 0x89, 0x02, 0x49, 0xcb, 0xc9, 0x5b, 0xe4, 0x29, 0x32, 0xe4, 0x49, 0x3c,
	0x05, 0x1e, 0x33, 0x25, 0x81, 0xfd, 0x22, 0x81, 0x48, 0x19, 0xf6, 0x90, 0x31, 0x93, 0x0e, 0xa7,
	0xff, 0xfe, 0xff, 0x3b, 0xf0, 0xe0, 0x0f, 0x26, 0x4c, 0xce, 0xcd, 0x5a, 0xaa, 0x05, 0x51, 0x25,
	0xd7, 0x46, 0xe4, 0x29, 0x29, 0x43, 0x92, 0xf2, 0x9c, 0x6b, 0xa1, 0x71, 0xa1, 0xa4, 0x91, 0xfe,
	0xb7, 0xa3, 0x0a, 0x1f, 0x54, 0xb8, 0x0c, 0xfb, 0x5f, 0x53, 0x99, 0x4a, 0x2b, 0x21, 0x55, 0xe5,
	0xd4, 0x7d, 0x94, 0x48, 0x9d, 0x49, 0x4d, 0x18, 0xd5, 0x9c, 0x94, 0x21, 0xe3, 0x86, 0x86, 0x24,
	0x91, 0x22, 0x77, 0xff, 0x47, 0x0f, 0x00, 0x7e, 0xfa, 0xeb, 0xfc, 0xcf, 0x0c, 0x35, 0xdc, 0xff,
	0x0d, 0xdb, 0x05, 0x55, 0x34, 0xd3, 0x3d, 0x30, 0x04, 0x41, 0x67, 0x8a, 0xf0, 0xdb, 0x79, 0xf8,
	0xbf, 0x55, 0x45, 0xad, 0xcd, 0xd3, 0xc0, 0x8b, 0xeb, 0x19, 0xdf, 0x87, 0xad, 0x4b, 0x25, 0xb3,
	0x5e, 0x63, 0x08, 0x82, 0x8f, 0xb1, 0xad, 0xfd, 0x25, 0xec, 0x88, 0x5c, 0x98, 0x99, 0xe2, 0x6b,
	0xaa, 0xe6, 0xbd, 0xe6, 0xb0, 0x19, 0x74, 0xa6, 0xdf, 0xb1, 0x03, 0xc3, 0x15, 0x18, 0xae, 0xc1,
	0xf0, 0x1f, 0x29, 0xf2, 0x68, 0x52, 0x39, 0xde, 0x3f, 0x0f, 0x82, 0x54, 0x98, 0xab, 0x15, 0xc3,
	0x89, 0xcc, 0x48, 0xbd, 0x85, 0xfb, 0x8c, 0xf5, 0x7c, 0x41, 0xcc, 0x4d, 0xc1, 0xb5, 0x1d, 0xd0,
	0x31, 0xac, 0xfc, 0x63, 0x6b, 0x3f, 0xba, 0x03, 0xb0, 0xed, 0xd0, 0xfc, 0x9f, 0xb0, 0xcb, 0x73,
	0xca, 0x96, 0x7c, 0x56, 0x63, 0xdb, 0x95, 0x3e, 0xc4, 0x9f, 0x5d, 0xf7, 0xdc, 0x35, 0xfd, 0x15,
	0xfc, 0x52, 0x70, 0x35, 0x63, 0x4b, 0x99, 0x2c, 0x0e, 0x90, 0x8d, 0xf7, 0x87, 0xec, 0x16, 0x5c,
	0x45, 0x55, 0x86, 0x03, 0x8d, 0xfe, 0x6d, 0x76, 0x08, 0x6c, 0x77, 0x08, 0xbc, 0xec, 0x10, 0xb8,
	0xdd, 0x23, 0x6f, 0xbb, 0x47, 0xde, 0xe3, 0x1e, 0x79, 0x17, 0x93, 0x13, 0x4f, 0x26, 0xcc, 0x9c,
	0xca, 0xb1, 0x90, 0xe4, 0xe4, 0x38, 0xae, 0x8f, 0xe7, 0x61, 0x13, 0x58, 0xdb, 0x3e, 0xe6, 0xaf,
	0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x73, 0x13, 0xdf, 0x42, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InitReward) > 0 {
		for iNdEx := len(m.InitReward) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitReward[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PerBlockReward) > 0 {
		for iNdEx := len(m.PerBlockReward) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerBlockReward[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.EnableVesting {
		i--
		if m.EnableVesting {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.InitReward) > 0 {
		for _, e := range m.InitReward {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EnableVesting {
		n += 2
	}
	if len(m.PerBlockReward) > 0 {
		for _, e := range m.PerBlockReward {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitReward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitReward = append(m.InitReward, types.Coin{})
			if err := m.InitReward[len(m.InitReward)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableVesting", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableVesting = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerBlockReward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerBlockReward = append(m.PerBlockReward, types.Coin{})
			if err := m.PerBlockReward[len(m.PerBlockReward)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
