name: "Pull Request Labeler"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
